### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by lds1998** [L3vi47h4N/Viper4Linux#14] opened 2019-01-07 02:30 UTC
I used yay -S viper4linux-git to get most of the work done.
then configured device.conf with desc="Speakers" location=alsa_output.pci-0000_00_1f.3.analog-stereo
When started viper gives this: 

Setting original sink to full volume...
Changing primary sink to Viper...
Moving existing audio streams to Viper...
WARNING: erroneous pipeline: no element "pulsesrc"

If asked for a status:
[ERROR]
There is a pidfile. However, there is no process running with the expected pid.
There is an idfile. The viper sink seems to be loaded at id: 98.

OS: Manjaro Linux

**Comment by yochananmarqos** [comment] 2019-01-07 02:35
Remove the device.conf and try again. It shouldn't be normally necessary unless the default sound device bis not detected.

**Comment by lds1998** [comment] 2019-01-07 02:37
Just removed the device.conf file and problem remains.

**Comment by yochananmarqos** [comment] 2019-01-07 02:43
I'm using Manjaro as well and I can't reproduce it. Are you sure the dependencies were installed?

**Comment by lds1998** [comment] 2019-01-07 02:52
I just rebooted the computer and well the problem fix itself all. Thank you anyway.
Should I delete this?

**Comment by yochananmarqos** [comment] 2019-01-07 02:54
You can close the issue.

**Closed** 2019-01-07 02:58 UTC

**Comment by L3vi47h4N** [comment] 2019-01-07 03:38
Thanks for taking care of this @yochananmarqos
